### ISSUE TITLE
Kemal::NullLogHandler does not work if there are present websocket routes

### ISSUE THREAD

**Issue by edersohe** [kemalcr/kemal#376]
##### Versions
```yml
crystal: 0.23.0
kemal:
    github: kemalcr/kemal
    commit: dbbe05a610e3c86b774a6bc546341329a408fa18
```
##### Kemal::NullLogHandler works, the logger doesn't prints anything, there aren't present websocket routes 
```crystal
require "kemal"

get "/" do |env|
  "this is a test"
end

Kemal.config.logger = Kemal::NullLogHandler.new
Kemal.run
```
##### Kemal::NullLogHandler does not works, the logger still prints the call to any route, apparently because a websocket route is present
```crystal
require "kemal"

ws "/" do |socket|
  socket.send("this is a test")
end

get "/" do |env|
  "this is a test"
end

Kemal.config.logger = Kemal::NullLogHandler.new
Kemal.run
```
