### ISSUE TITLE
Error compile example Cemal?

### ISSUE THREAD

**Issue by nesteg** [kemalcr/kemal#417]
I'm Write web-cemal.cr >>
"require "kemal"

get "/" do
  "Hello World!"
end

Kemal.run"

then command "crystal run src/web-kemal.cr"
 and get error:undefined method 'open' for Flate::Writer:Class
???((:
Linux U-buntu on Windows 10

Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1

**Comment by nesteg** [comment]
Oops!!
[http://prntscr.com/h774i2](url)

**Comment by sdogruyol** [comment]
Please use Kemal `0.21.0` instead of master.

```yml
dependencies:
  kemal:
    github: kemalcr/kemal
    version: 0.21.0
```
