### ISSUE TITLE
can't compile fresh example app with kemal. 

### ISSUE THREAD

**Issue by salzig** [kemalcr/kemal#422]
### Description

Can't build example app 

### Steps to Reproduce

```
crystal init app kemal_example
cd kemal_example
# change src/kemal_example.cr
# change shard.yml
shards install
crystal run src/kemal_example.cr
```

`shard.yml`
```
name: kemal_example
version: 0.1.0

authors:
  - Ben Rexin <ben@rexin.at>

targets:
  kemal_example:
    main: src/kemal_example.cr

dependencies:
  kemal:
    github: kemalcr/kemal
    branch: master

crystal: 0.23.1

license: MIT
```

`src/kemal_example.cr`
```
require "kemal"

get "/" do
  "Hello World!"
end

Kemal.run

```

**Expected behavior:** 

I expected it to compile

**Actual behavior:** 

```
Error in src/kemal_example.cr:7: instantiating 'Kemal:Module#run()'

Kemal.run
      ^~~

in lib/kemal/src/kemal.cr:19: instantiating 'Kemal:Module#run(Nil)'

    self.run(nil)
         ^~~

in lib/kemal/src/kemal.cr:12: instantiating 'Kemal:Module#run(Nil)'

    self.run port do
         ^~~

in lib/kemal/src/kemal.cr:55: instantiating 'send_file(HTTP::Server::Context, String)'

          send_file env, file_path
          ^~~~~~~~~

in lib/kemal/src/kemal/helpers/helpers.cr:126: instantiating 'File:Class#open(String)'

  File.open(file_path) do |file|
       ^~~~

in lib/kemal/src/kemal/helpers/helpers.cr:126: instantiating 'File:Class#open(String)'

  File.open(file_path) do |file|
       ^~~~

in lib/kemal/src/kemal/helpers/helpers.cr:137: undefined method 'open' for Flate::Writer:Class

      Flate::Writer.open(env.response) do |deflate|
```

**Reproduces how often:** 

so far 100%

### Versions

- Crystal 0.23.1 (2017-10-12) LLVM 4.0.1

**Comment by sdogruyol** [comment]
Please use `0.21.0` with Crystal `0.23.1`.

```yml
dependencies:
  kemal:
    github: kemalcr/kemal
    version: 0.21.0
```
