### ISSUE TITLE
redirect with flash session #375

### ISSUE THREAD

**Issue by lebogan** [kemalcr/kemal#444]
Is kemal-flash still a valid shard? Using it with kemal-sessions doesn't seem to work. I have tested it with Chrome, Firefox, and Opera. What am I missing? Crystal 0.24.2, Kemal 0.22.0.
```
 kemal-flash:
    github: neovintage/kemal-flash
    version: 0.1.0

  kemal-session:
    github: kemalcr/kemal-session
    version: 0.9.0
```
```
require "kemal"
require "kemal-session"
require "kemal-flash"

get "/check_flash" do |env|
  env.flash["notice"]?
end
```
Thanks as always :)
