### ISSUE TITLE
No static files served when deployed behind apache2/mod_proxy

### ISSUE THREAD

**Issue by erpe** [kemalcr/kemal#481]
### Description

Static files under directory 'public' is not served when kemal is deployed behind apache/mod_proxy.
my directory structure is:

```
- src/
- public/
 - assets/
  - stylesheets/
   - styles.css
```
on my layout i try to load the style with:
`<link rel='stylesheet' href='/assets/stylesheets/styles.css' />`

my virtualhost is like:

```
<VirtualHost *:80>
    ServerName mydom.com
    ServerAdmin hostmaster@mydom.com
    ErrorLog ${APACHE_LOG_DIR}/mydom_error.log
    CustomLog ${APACHE_LOG_DIR}/mydom_access.log combined
    ProxyPass / http://127.0.0.1:3000/
    ProxyPassReverse / http://127.0.0.1:3000/
</VirtualHost>
```
Deployment is done with capistrano - 
see @sdogruyol 's gist: https://gist.github.com/sdogruyol/d19361ffa9115454064f9379e8dc7e40

Accessing the deployed app via browser works as expected - **except** for the static file will result in 404.
When running the app local and pointing my browser to 127.0.0.1:3000 - everything is fine  - also a request to the static css-file succeeds.

Only workaround for me is to not start/stop kemal with above mentioned cap-tasks, but to 
cd in directory structure on server: 

**works / delivers static files:**
```
cd /var/www/domain/current; 
./app;
```
**not works / no static files:**
```
cd /var/www/domain/releases/20180813202152
./app
```
seems like it could have something to do links set by capistrano...

### Versions

Crystal 0.25.1 [b782738ff] (2018-06-27)

in shards.lock:
```
shards:
  kemal:
    github: kemalcr/kemal
    version: 0.23.0

  kemal-session:
    github: kemalcr/kemal-session
    version: 0.10.0

  kilt:
    github: jeromegn/kilt
    version: 0.4.0

  radix:
    github: luislavena/radix
    version: 0.3.8

  spec-kemal:
    github: kemalcr/spec-kemal
    version: 0.4.0

```
I am not sure, if this is a bug or just my missing experience with kemal. so please bare with me in the latter case...
