### ISSUE TITLE
Strange behaviour on greedy routes (/*)

### ISSUE THREAD

**Issue by drakmail** [kemalcr/kemal#489]
### Description

I have following routes definition:

```ruby
require "kemal"

get "/*" do
  "default route"
end

get "/refresh" do
  "refresh route"
end

Kemal.run
```

When I request `/request1234` instead of "default route" response I got 404 error page.

### Steps to Reproduce

1. Run example
2. curl http://localhost:3000/sometest and get "default route" response
3. curl http://localhost:3000/refresh and get "refresh route" response
4. curl http://localhost:3000/refresh1234 and get unexpected "404 page" response (in html)

**Expected behavior:** "default route" response

**Actual behavior:** 404 page in html

**Reproduces how often:** every time

### Versions

```bash
$ crystal --version
Crystal 0.26.1 (2018-08-27)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

```yaml
# shard.lock
version: 1.0
shards:
  exception_page:
    github: crystal-loot/exception_page
    version: 0.1.1

  kemal:
    github: kemalcr/kemal
    version: 0.24.0

  kilt:
    github: jeromegn/kilt
    version: 0.4.0

  radix:
    github: luislavena/radix
    version: 0.3.8
```
