### ISSUE TITLE
Cannot get kemal through shards that has the fix for Crystal 0.35

### ISSUE THREAD

**Issue by arjunepr** [kemalcr/kemal#572]
### Description
Can't get the latest version of Kemal with fix for crystal 0.35
[Description of the issue]

I've been trying to run a simple test, running just the example application given in the readme. But I keep getting the `Error: undefined constant Gzip::Writer` error when I try to run. I've noticed that the latest changes for Crystal 0.35 have been met with [#570](https://github.com/kemalcr/kemal/pull/570)

### Steps to Reproduce

1. Add dependency for kemal to the shards.yml file. I've tried to set branch as master and give a git link to the project repository
2. delete out the contents of the lib folder if needed and run `shards install`
3. Run a simple example based on what's provided as an example in the front page

**Expected behavior:** [What you expect to happen]
Everything working as expected

I think if the version in the shards.yml file is bumped up from 0.26.1 to something like 0.26.2 this wouldn't be a problem since shards seems to pull in the latest version based on the tag

**Comment by Blacksmoke16** [comment]
Yes, a new release needs to be created that contains the comparability PR for `0.35.0`.  In the meantime you can do:

```yaml
dependencies:
  kemal:
    github: kemalcr/kemal
    branch: master
```

**Comment by arjunepr** [comment]
Yes, you're right - for some reason I thought the method of specifying the master branch wasn't working and I was about to make a comment here that I was able to get a workaround through specifying the commit instead

Basically

```yaml
dependencies:
  kemal:
    git: https://github.com/kemalcr/kemal.git
    commit: a8c0f09b858162bd13c96663febef5527b322a32
```

The method you've provided @Blacksmoke16 works well and this is all that's needed after all. Thanks for responding and being considerate with this noob question! I'll close what I've made here since there's likely actual issues to deal with, and hopefully this would at least help someone if they're just starting to get acquainted
