### ISSUE TITLE
Heroku deployment issue due to Gzip:Writer

### ISSUE THREAD

**Issue by marcstein** [kemalcr/kemal#580]
Running locally using Crystal 35.0 and Kemal 0.26.1 everything compiles and runs fine. When I deploy to Heroku though it seems to revert to the earlier version of helpers.cr and generates the error 

remote: In lib/kemal/src/kemal/helpers/helpers.cr:143:7
remote:
remote:  143 | Gzip::Writer.open(env.response) do |deflate|
remote:        ^
remote: Error: undefined constant Gzip::Writer
remote:  !     Push rejected, failed to compile Crystal app.
remote:
remote:  !     Push failed

It seems like the wrong version is being pulled when Heroku updates the shards. Any idea how to resolve?

Thanks!

**Comment by notdaniel** [comment]
I imagine this is the same issue as #571, #572, #573. #574. Fixed, but is pending a new release.

In the meantime, it should work by specifying the commit in your shards.yml:

```yaml
dependencies:
  kemal:
    github: kemalcr/kemal
    commit: a8c0f09b858162bd13c96663febef5527b322a32
```

This has worked for me and others.
