### ISSUE TITLE
Slang doesn't render anymore

### ISSUE THREAD

**Issue by renich** [kemalcr/kemal#633]
### Description
I dunno what changed in v1.1.1 but, since then, slang doesn't render. No error either. 

### Steps to Reproduce

1. Use kemal v1.1.1
2. Try rendering some slang.

**Expected behavior:** [What you expect to happen]
I would expect slang to be rendered and get some html.

**Actual behavior:** [What actually happens]
I get the slang source code. 

**Reproduces how often:** [What percentage of the time does it reproduce?]
Every time.

### Versions

```bash
[renich@introdesk myapp]$ shards
Resolving dependencies
Fetching https://github.com/kemalcr/kemal.git
Fetching https://github.com/luislavena/radix.git
Fetching https://github.com/jeromegn/kilt.git
Fetching https://github.com/crystal-loot/exception_page.git
Fetching https://github.com/sija/backtracer.cr.git
Fetching https://github.com/jeromegn/slang.git
Using radix (0.4.1)
Using kilt (0.6.1)
Using backtracer (1.2.1)
Using exception_page (0.2.2)
Using kemal (1.1.0 at 523340b)
Using slang (1.7.3 at 901df64)

[renich@introdesk myapp]$ crystal version
Crystal 1.3.2 (2022-01-18)

LLVM: 13.0.0
Default target: x86_64-redhat-linux-gnu
```

Running on Fedora 35.

### Additional Information
It seems that you removed kilt and that caused the issues. The following shard.yml file will not be sufficient in v1.1.1:

```yaml
name: myapp
version: 0.1.0
license: MIT

authors:
  - Renich Bon Ćirić <renich@woralelandia.com>

description: |
  App de ejemplo.

dependencies:
  kemal:
    github: kemalcr/kemal
    tag: v1.1.1

  slang:
    github: jeromegn/slang
    tag: v1.7.3
```

It does work with v1.1.0 though.
